name: Secrets And Environment
on: workflow_dispatch
env:
  LEVEL: workflow
jobs:
  env-levels:
    runs-on: ubuntu-latest
    env:
      LEVEL: job
    steps:
      - name: print env level
        run: |
          echo "Level: $LEVEL"
      - name: print step env level
        run: |
          echo "Level2: $LEVEL"
        env:
          LEVEL: step
