name: Secrets And Environment
on: workflow_dispatch
env:
  LEVEL: workflow
jobs:
  env-levels:
    runs-on: ubuntu-latest
    env:
      LEVEL: job
    steps:
      - name: print env level
        run: |
          echo "Level: $LEVEL"
      - name: print step env level
        run: |
          echo "Level2: $LEVEL"
        env:
          LEVEL: step

      - name: Print step env level again
        run: |
          echo "Level2: $LEVEL"
  propagating-values:
    runs-on: ubuntu-latest
    steps:
      - name: Export a variable
        run: |
          export VAR1=training-room-6.3
          echo "In this step VAR1= $VAR1"
      - name: Using the exported variable
        run: |
          echo "In this step VAR1= $VAR1"

      - name: Add variable to GitHub Env
        run: |
          echo "VAR1=training-room-6.3" >> "$GITHUB_ENV"

      - name: Use variable from GitHub Env
        run: |
          echo "VAR1=$VAR1"
      
