
name: Composite Actions
on: workflow_dispatch

jobs:
  use-the-action:
    runs-on: ubuntu-latest
    steps:
      - name: React action Setup
        id: react-action-setup
        uses: ./.github/actions/reaction-action-setup
        with:
          node-version: '24.x'
          
